
class RadialPositions {
    const RADIAL_ICON_SIZE = 18;

    const RADIAL_POSITION_WEATHER = 0;
    const RADIAL_POSITION_ALARM = 30;
    const RADIAL_POSITION_DATE = 90;
    const RADIAL_POSITION_PHONE_CONNECTION = 50;
    const RADIAL_POSITION_PHONE_NOTIFICATIONS = 50;
    const RADIAL_POSITION_WATCH_BATTERY = 70;

    const RADIAL_GOAL_START_ARC = 230.0;
    const RADIAL_GOAL_START_LENGTH = 90.0;

    const RADIAL_HEART_RATE_ICON = 208;
}