
class RadialPositions {
	const RADIAL_ICON_SIZE = 20;
	
	const RADIAL_POSITION_ALARM = 60;
	const RADIAL_POSITION_DATE = 90;
	const RADIAL_POSITION_PHONE_CONNECTION = 30;
	const RADIAL_POSITION_PHONE_NOTIFICATIONS = 30;
}