
class RadialPositions {
	const RADIAL_ICON_SIZE = 18;
	
	const RADIAL_POSITION_ALARM = 60;
	const RADIAL_POSITION_DATE = 90;
	const RADIAL_POSITION_PHONE_CONNECTION = 40;
	const RADIAL_POSITION_PHONE_NOTIFICATIONS = 40;
	const RADIAL_POSITION_WATCH_BATTERY = 20;
}